// Food types
export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const GET_CART_NUM = "GET_CART_NUM";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const FETCH_CART_ITEMS = "FETCH_CART_ITEMS";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const CALCULATE_CART_TOTAL = "CALCULATE_CART_TOTAL";
export const CALCULATE_CART_QUANTITY = "CALCULATE_CART_QUANTITY";
export const REMOVED_CART_ITEM = "REMOVED_CART_ITEM";
export const GET_ORDER_ID = "GET_ORDER_ID";
export const SET_LOADING = "SET_LOADING";
export const SET_ORDER_LOADING = "SET_ORDER_LOADING";
export const SHOW_CART_POP_UP = "SHOW_CART_POP_UP";
export const HIDE_CART_POP_UP = "HIDE_CART_POP_UP";
export const OPEN_CART = "OPEN_CART";
export const CLOSE_CART = "CLOSE_CART";

// User
export const FETCH_USER = "FETCH_USER";
export const FETCH_TOKEN = "FETCH_TOKEN";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const USER_AUTHORIZED = "USER_AUTHORIZED";
export const USER_UNAUTHORIZED = "USER_UNAUTHORIZED";

// Location
export const OPEN_LOCATION = "OPEN_LOCATION";
export const CLOSE_LOCATION = "CLOSE_LOCATION";

// Errors
export const FOOD_ERROR = "FOOD_ERROR";
export const PAYMENT_ERROR = "PAYMENT_ERROR";
